version: '3'

services:
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: f1_module
    networks:
      - my_network

  flask_app1:
    build:
      context: ./flask_app
      dockerfile: Dockerfile
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: f1_module
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    networks:
      - my_network
    
  flask_app2:
    build:
      context: ./flask_app
      dockerfile: Dockerfile
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: f1_module
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "5001:5000" 
    depends_on:
      - mysql
    networks:
      - my_network
  # Website accessible at address : localhost:80
  nginx_load_balancer:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - flask_app1
      - flask_app2
    networks:
      - my_network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  #Work environment accessible at address 0.0.0.0:5005 not linked to the load balancer to work there
  flask_app_work_env:
    build:
      context: ./flask_app
      dockerfile: Dockerfile
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: f1_module
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "5005:5000"
    depends_on:
      - mysql
    networks:
      - my_network
  # When modify with an error python flask shutdown due to my dockerfile the container shut dow so I restart will docker-compose is up
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}" 
    volumes:
      - ./flask_app/Axel-LANTA-MSCC-CPA-assignment1Code-3119123:/app


networks:
  my_network:
    driver: bridge

volumes:
  mysql_data:
